language: objective-c
rvm: 1.9.3

before_install:
    - brew update
    - brew install xctool
script: xctool ARCHS=i386 VALID_ARCHS=i386 CURRENT_ARCH=i386 ONLY_ACTIVE_ARCH=NO -workspace 'LLSemanticLayout.xcworkspace' -scheme 'LLSemanticLayout' -configuration Debug -sdk iphonesimulator clean build test
