language: objective-c
rvm: 1.9.3

script: xctool -workspace 'LLSemanticLayout.xcworkspace' -scheme 'LLSemanticLayout' -configuration Debug -sdk iphonesimulator clean build test -freshSimulator -freshInstall ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
